version: '2'
services:
  webapp2_setup:
    build: .
    depends_on:
      - postgres
    environment:
      - PASSENGER_APP_ENV=development
    entrypoint: ./setup.sh
  webapp2:
    container_name: webapp2
    build: .
    depends_on:
      - postgres
      - webapp2_setup
    environment:
      - PASSENGER_APP_ENV=development
    ports:
      - "80:80"
    volumes:
      - .:/home/app/webapp2
  postgres:
    image: postgres:9.5.3
    environment:
      - POSTGRES_PASSWORD=mysecretpassword
      - POSTGRES_USER=webapp2
      - POSTGRES_DB=webapp2_development
    volumes_from:
      - postgres_data
  postgres_data:
    image: postgres:9.5.3
    volumes:
      - /var/lib/postgresql/data
    command: /bin/true
